# -*- coding: utf-8 -*-
"""MLUtilities.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EFVDJiY_Uvs6DWpG5_3YurhXPwgeu6Fk
"""

# EQUIPO 10 - BEDU

# Funciones de separación de entrenamiento, validación y prueba.

# Funciones de separación de datasets con K-Fold (el usuario debe poner el K, si K = 1 debe generar un Leave-One-Out Cross Validation).

# Funciones de evaluación con matriz de confusión.

# Funciones de obtención de Precisión (Accuracy), Sensibilidad y Especificidad

# Funciones que comparen dos clasificadores:
# Obtener precisión, sensibilidad y especificidad del clasificador 1
# Obtener precisión, sensibilidad y especificidad del clasificador 2
# Indicar cual es mejor en terminos de precisión
# Indicar cual es mejor en términos de sensibilidad
# Indicar cual es mejor en términos de especificidad.